### ISSUE TITLE
Cell doesn’t run in binder

### ISSUE THREAD

**Issue by KirstieJane** [malvikasharan/Alignment-Algorithms#2]
Heya! I love this tutorial!

I found a cell that doesn’t import properly in the binder. Screenshot attached 😸

There’s also a markdown formatting error - I think you need a space before the `...` ✨

![A4EB94D1-D3E3-48D1-A960-8506EDAA1585](https://user-images.githubusercontent.com/3626306/59587906-4669f780-90de-11e9-8cc2-e0de8a492c9c.png)

 
![62119910-587E-4CF2-B11B-DB56AC3284CF](https://user-images.githubusercontent.com/3626306/59587907-4669f780-90de-11e9-8ac4-2c4cc756d408.png)

**Comment by malvikasharan** [comment]
Oh thank you. I didn't add 'bio' on requirements file. thank you checking <3

**Comment by malvikasharan** [comment]
@KirstieJane I was unable to rebuild the binder after updating the requirement file with biopython. In the end, I replicated this repo with the correct requirement file and built the binder that worked. Do you know how to update an existing binder?

**Comment by KirstieJane** [comment]
It should just re-build automatically. The binder link works for me now.

There's a new error though:

    with open('blosum62.bla', 'r') as in_fh:

should be

    with open('blosum62.txt', 'r') as in_fh:

**Comment by malvikasharan** [comment]
Ah, I hadn't tested it after my interview. It didn't work immediately and I assumed that it needs a special command to force rebuilding. Thanks for checking!

**Comment by malvikasharan** [comment]
Also, corrected the file name.
